// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// GetScriptResponse defines model for GetScriptResponse.
// type GetScriptResponse struct {
// 	AccessGroup    *string        `json:"accessGroup,omitempty"`
// 	Attachments    *[]interface{} `json:"attachments,omitempty"`
// 	Code           *string        `json:"code,omitempty"`
// 	CreatedAt      *string        `json:"createdAt,omitempty"`
// 	CreatedBy      *string        `json:"createdBy,omitempty"`
// 	Id             int            `json:"id"`
// 	Interpreter    *string        `json:"interpreter,omitempty"`
// 	IsEditable     *bool          `json:"isEditable,omitempty"`
// 	IsExecutable   *bool          `json:"isExecutable,omitempty"`
// 	IsRedactable   *bool          `json:"isRedactable,omitempty"`
// 	LastEditedBy   *string        `json:"lastEditedBy,omitempty"`
// 	ScriptProfiles *[]interface{} `json:"scriptProfiles,omitempty"`
// 	Status         *string        `json:"status,omitempty"`
// 	TimeLimit      *int           `json:"timeLimit,omitempty"`
// 	Title          string         `json:"title"`
// 	Username       *string        `json:"username,omitempty"`
// 	Version        *int           `json:"version,omitempty"`
// }

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetScript request
	GetScript(ctx context.Context, scriptId int, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetScript(ctx context.Context, scriptId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetScriptRequest(c.Server, scriptId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetScriptRequest generates requests for GetScript
func NewGetScriptRequest(server string, scriptId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "scriptId", runtime.ParamLocationPath, scriptId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/scripts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetScriptWithResponse request
	GetScriptWithResponse(ctx context.Context, scriptId int, reqEditors ...RequestEditorFn) (*GetScriptResponse, error)
}

type GetScriptResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetScriptResponse
	JSON404      *UnauthorizedError
}

// Status returns HTTPResponse.Status
func (r GetScriptResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetScriptResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetScriptWithResponse request returning *GetScriptResponse
func (c *ClientWithResponses) GetScriptWithResponse(ctx context.Context, scriptId int, reqEditors ...RequestEditorFn) (*GetScriptResponse, error) {
	rsp, err := c.GetScript(ctx, scriptId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetScriptResponse(rsp)
}

// ParseGetScriptResponse parses an HTTP response from a GetScriptWithResponse call
func ParseGetScriptResponse(rsp *http.Response) (*GetScriptResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetScriptResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetScriptResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UnauthorizedError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
